/**
 * @file        main.cpp
 * @author      Fran Fodor for Soldered
 * @brief       Example showing how to display an image on Inkplate 6
 *              using the Soldered Image Converter tool.
 *
 * @details     This example demonstrates how to use the Soldered Image
 *              Converter to prepare an image for display on Inkplate 6.
 *              The tool converts any image into a C byte array stored in
 *              a header file (.h) which can be directly included.
 *
 *              Tool workflow:
 *              1. Open the Image Converter at
 * https://tools.soldered.com/tools/image-converter/
 *              2. Upload your image and select "Inkplate 6" as the target
 * board.
 *              3. Choose the display mode:
 *                 - 1-bit (Black & White) - fastest refresh, highest contrast
 *                 - 3-bit (Grayscale) - 8 shades of gray
 *              4. Adjust dithering, resize, and other options as needed.
 *              5. Save the generated header file (image_ex.h) and place it
 *                 in the same folder as this sketch.
 *
 * Requirements:
 * - Board:      Soldered Inkplate 6
 * - Framework:  ESP-IDF v6.x
 * - Hardware:   Inkplate 6, USB cable
 * - Extra:      The image header file (image_ex.h) generated by the tool
 *
 * Configuration:
 * - Menuconfig -> Inkplate Boards -> Inkplate6
 *
 * How to use:
 * 1) Generate image_ex.h using the Image Converter at
 * https://tools.soldered.com/tools/image-converter/ 2) Place image_ex.h in the
 * same folder as this sketch. 3) Build and flash to Inkplate 6. 4) The image
 * appears on the display after initialization.
 *
 * Expected output:
 * - Your converted image displayed on the Inkplate 6 e-paper screen.
 *
 * Notes:
 * - image_w and image_h are automatically defined in the generated image_ex.h.
 * - For grayscale mode use INKPLATE_3BIT instead of INKPLATE_1BIT.
 * - display.clearDisplay() clears only the internal framebuffer.
 * - display.display() must be called to push the framebuffer to the screen.
 * - To change the display mode, the image has to be compatible with it.
 *
 * Docs:         https://docs.soldered.com/inkplate
 * Support:      https://forum.soldered.com/
 * Image tool:   https://tools.soldered.com/tools/image-converter/
 */

#include "sdkconfig.h"

#ifndef CONFIG_INKPLATE_BOARD_INKPLATE6
#error                                                                         \
    "Wrong board selection for this example, please select Inkplate6 in the boards menu."
#endif

#include "Inkplate.h"
#include "image_ex.h"

extern "C" void app_main(void) {
  Inkplate display;

  display.setDisplayMode(BLACK_AND_WHITE); // Set display mode to 1-bit (black & white)

  display.clearDisplay(); // Clear frame buffer of display
  // Display selected picture at location X=0, Y=0.
  display.image.draw(image, 0, 0, image_w, image_h, BLACK);
  display.display(); // Refresh the screen with new picture
}
