idf_component_register(SRCS "src/features/I2C.cpp" "src/features/RTC.cpp" "src/features/PCAL.cpp" "src/features/I2S.cpp" "src/features/TPS.cpp"
                             "src/features/Network.cpp"
                             "src/features/SDCard.cpp"
                             "src/boards/inkplate6/Inkplate6.cpp"
                             "src/boards/inkplate10/Inkplate10.cpp"
                             "src/boards/Inkplate.cpp"
                             "src/graphics/Graphics.cpp"
                             "src/graphics/Image/Image.cpp"
                             "src/graphics/Image/BMP/BMP.cpp"
                             "src/graphics/Image/JPEG/JPEG.cpp"
                             "src/graphics/Image/PNG/PNG.cpp"
                             "src/graphics/pngle/pngle.c"
                             "src/graphics/Adafruit_GFX/Adafruit_GFX.cpp"
                             "src/graphics/Shapes/Shapes.cpp"
                             "src/graphics/Shapes/ShapesPolygon.cpp"
                       REQUIRES "esp_driver_i2c" "esp_driver_i2s" "esp_driver_gpio" "esp_timer" "esp_adc"
                                "esp_driver_spi" "fatfs" "sdmmc"
                                "esp_wifi" "nvs_flash" "esp_http_client"
                       INCLUDE_DIRS "include" "include/features" "include/boards" "include/boards/inkplate6" "include/boards/inkplate10"
                                    "include/graphics" "include/graphics/Adafruit_GFX" "include/graphics/Shapes"
                                    "include/graphics/Image"
                                    "include/graphics/Image/BMP"
                                    "include/graphics/Image/JPEG"
                                    "include/graphics/Image/PNG"
                                    "include/graphics/pngle")
